apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "presence-service.fullname" . }}
  labels:
    {{- include "presence-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "presence-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "presence-service.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.deployment.securityContext | nindent 8 }}
      containers:
      - name: presence-service
        image: {{ include "presence-service.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.networking.servicePort }}
          protocol: TCP
        {{- if eq .Values.service.nodeType "center" }}
        - name: nats
          containerPort: {{ .Values.networking.natsPort }}
          protocol: TCP
        - name: nats-leaf
          containerPort: {{ .Values.networking.natsLeafPort }}
          protocol: TCP
        - name: nats-cluster
          containerPort: {{ .Values.networking.natsClusterPort }}
          protocol: TCP
        {{- end }}
        env:
        {{- include "presence-service.env" . | nindent 8 }}
        {{- with .Values.deployment.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: data
          mountPath: {{ .Values.nats.dataDir }}
        {{- end }}
        - name: tmp
          mountPath: /tmp
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "presence-service.fullname" . }}-data
      {{- end }}
      - name: tmp
        emptyDir: {}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}